TF_IDF means term frequency-inner document frequency

Term Frequency (TF): Measures how often a word appears in a document. A higher frequency suggests greater importance. If a term appears frequently in a document, it is likely relevant to the document’s content.

Inverse Document Frequency (IDF): Reduces the weight of common words across multiple documents while increasing the weight of rare words. If a term appears in fewer documents, it is more likely to be meaningful and specific.

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

d0 = 'Good Boy'
d1 = 'Good Girl'
d2 = 'Boy Girl Good'
string = [d0, d1, d2]
tfidf = TfidfVectorizer(max_features=10,ngram_range=(1,2),binary=True)
result = tfidf.fit_transform(string).toarray()

np.set_printoptions(edgeitems=5, linewidth=100000,formatter= dict(float= lambda x: "{:0.4f}".format(x)))

result

print('\nidf values:')
for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)


idf values:
boy : 1.2876820724517808
boy girl : 1.6931471805599454
girl : 1.2876820724517808
girl good : 1.6931471805599454
good : 1.0
good boy : 1.6931471805599454
good girl : 1.6931471805599454


In [12]:
print('\nWord indexes:')
print(tfidf.vocabulary_)
print('\ntf-idf value:')
print(result)
print('\ntf-idf values in matrix form:')
print(result.toarray())


Word indexes:
{'good': np.int64(2), 'boy': np.int64(0), 'girl': np.int64(1)}

tf-idf value:
[[0.7898 0.0000 0.6134]
 [0.0000 0.7898 0.6134]
 [0.6198 0.6198 0.4813]]

tf-idf values in matrix form:


AttributeError: 'numpy.ndarray' object has no attribute 'toarray'